import { Compunknown } from "./compunknown";
import IdValue from "./idValue";
import IdValueList from "./idValueList";

export interface Game {
    id: number;
    name: string;
    summary?: string;
    totalRating?: number;
    totalRatingCount?: number;
    url?: string;
    ageRatings?: IdValueList;
    aggregatedRating?: number | null;
    aggregatedRatingCount?: number | null;
    alternativeNames?: IdValueList;
    artworks?: unknown[] | null;
    bundles?: unknown[] | null;
    category?: string;
    checksum?: string;
    collections?: unknown[] | null;
    companies?: Compunknown[] | null;
    cover?: IdValue;
    createdAt?: string;
    dlcs?: unknown[] | null;
    expandedGames?: unknown[] | null;
    expansions?: unknown[] | null;
    externalGames?: IdValueList;
    firstReleaseDate?: string;
    forks?: unknown[] | null;
    franchise?: unknown | null;
    franchises?: IdValueList;
    gameEngines?: unknown[] | null;
    gameLocalizations?: unknown[] | null;
    gameModes?: IdValueList;
    genres?: IdValueList;
    hypes?: number | null;
    involvedCompanies?: IdValueList;
    keywords?: unknown[] | null;
    languageSupports?: unknown[] | null;
    multiplayerModes?: unknown[] | null;
    parentGame?: unknown | null;
    platforms?: IdValueList;
    playerPerspectives?: IdValueList;
    ports?: unknown[] | null;
    rating?: number;
    ratingCount?: number;
    releaseDates?: IdValueList;
    remakes?: unknown[] | null;
    remasters?: unknown[] | null;
    screenshots?: IdValueList;
    similarGames?: IdValueList;
    slug?: string;
    standaloneExpansions?: unknown[] | null;
    status?: string | null;
    storyline?: string | null;
    tags?: number[];
    themes?: IdValueList;
    updatedAt?: string;
    versionParent?: IdValue;
    versionTitle?: string;
    videos?: unknown[] | null;
    websites?: unknown[] | null;
  }